### ISSUE TITLE
Need Zip Format Support

### ISSUE THREAD

**Issue by wbraswell** [Perl5-Alien/Alien-Build-Plugin-Download-GitHub#19]
It is not correct to assume only "tar.gz" format files, because some GitHub repositories offer "zip" format files.
https://github.com/PerlAlien/Alien-Build-Plugin-Download-GitHub/blob/main/lib/Alien/Build/Plugin/Download/GitHub.pm#L135

**Comment by plicease** [comment]
Can you point me to the repo in question?  I agree this should handle other formats, but if you point me to an actual example will save me some time.

**Comment by plicease** [comment]
This is actually invalid because this plugin fetches the tarball link not the release link.
