### ISSUE TITLE
Should be able to specify no extractor

### ISSUE THREAD

**Issue by plicease** [Perl5-Alien/Alien-Build-Plugin-Download-GitHub#26]
For when the asset really is the thing that you need and it doesn't need to be further extracted!  I think the GitLab version of this already has this.

**Comment by zmughal** [comment]
Yes, I'm coming across this now particularly when I am downloading a binary release (`.exe`, `.msi`, `.pkg`) or when I must use a specific extractor plugin (e.g., `Extract::CommandLine`).

**Comment by plicease** [comment]
I was able to work around this by using 'f' as the asset "format"
https://metacpan.org/release/PLICEASE/Alien-ghostunnel-0.01/source/alienfile#L43
I still want to make it possible to turn this off in this plugin but I haven't gotten around to doing it yet.

**Comment by zmughal** [comment]
I still need to run my own extraction code, so I just used an `around_hook` that does not call the original. Not the best approach but works for now.

**Comment by plicease** [comment]
#27 should address this.  I sort of painted myself into a corner with this one, but with this PR if you set it to `none` it won't add an extractor, even if you are using the asset mode.  I can't think of a situation where you would really not want to extract in tag mode, since that is always a tarball, but no harm I think in having that option even if you never use it.

**Comment by plicease** [comment]
0.10 should address this!

**Comment by plicease** [comment]
hopefully we don't ever need to add an extractor called `none`.
