### ISSUE TITLE
error fetching https://api.github.com/repos/tukaani-project/xz/releases: 403 rate limit exceeded

### ISSUE THREAD

**Issue by max-m-s** [Perl5-Alien/Alien-Build-Plugin-Download-GitHub#30]
"error fetching https://api.github.com/repos/tukaani-project/xz/releases: 403 rate limit exceeded."

Thus builds requiring Alien::xz fail.

**Comment by plicease** [comment]
This is a limitation of GH.  If for some reason you are repeatedly rebuilding this module you should consider using a PAT:
https://metacpan.org/pod/Alien::Build::Plugin::Download::GitHub#CAVEATS
